# -*- encoding: utf-8 -*-

# This is a TEST file.
# It contains the arguments of the pipeline for functional verification of LSPE-STRIP (2023)
# The pathfile argument is wrong, hence it produce an Error.
# December 18th 2023, Bologna (Italy)

[official_pipeline_args]

########################################################################################################################
# Positional Arguments (mandatory)
########################################################################################################################
subcommand = 'tot'

# Wrong Argument
path_file = '../data_testtttt'

start_datetime='2023-03-13 00:00:00'
end_datetime='2023-03-13 00:02:01'
name_pol='all'

########################################################################################################################
# Flags (optional)
########################################################################################################################

# TOML
toml_file_path = "config/validation_config/config_tot.toml"

# TS Analysis
thermal_sensors = "true"
ts_sam_exp_med=20.0
ts_sam_tolerance=1.0

# HK Analysis
housekeeping = "true"
hk_sam_exp_med = "1.4, 1.4, 60.0"
hk_sam_tolerance = "0.1, 0.1, 0.5"

# Correlation Analysis
corr_plot= "true"
corr_mat= "true"
cross_corr= "false" # Set true for cross correlations
corr_t=0.4

# Scientific Analysis
even_odd_all='AOE'
scientific="true"
rms="true"
smooth=1
window=10
sam_tolerance=0.005

# Spectral Analysis
fourier="true"
# To reach a min freq of 10^-4 these are the nperseg requested
nperseg=500000
nperseg_thermal=500

# Spike Analysis
spike_data="true"
spike_fft="true"

# Output dir for plots and reports
output_plot_dir='../plot'
output_report_dir='../plot/Reports'
report_to_plot ='../..'
