language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install -r requirements.txt

install:
 - sudo apt-get update
 - sudo apt-get -y install python3-pyqt5

script:
  - black --check .
  - python -m pytest -vv
