# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1551, 1149)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.polarimeter_tree = QtWidgets.QTreeWidget(self.groupBox)
        self.polarimeter_tree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.polarimeter_tree.setObjectName("polarimeter_tree")
        self.horizontalLayout_4.addWidget(self.polarimeter_tree)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plotTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.plotTabWidget.setObjectName("plotTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pwr_q1 = BaseMplCanvas(self.tab)
        self.pwr_q1.setObjectName("pwr_q1")
        self.gridLayout_2.addWidget(self.pwr_q1, 0, 0, 1, 1)
        self.pwr_q2 = BaseMplCanvas(self.tab)
        self.pwr_q2.setObjectName("pwr_q2")
        self.gridLayout_2.addWidget(self.pwr_q2, 0, 1, 1, 1)
        self.pwr_u1 = BaseMplCanvas(self.tab)
        self.pwr_u1.setObjectName("pwr_u1")
        self.gridLayout_2.addWidget(self.pwr_u1, 1, 0, 1, 1)
        self.pwr_u2 = BaseMplCanvas(self.tab)
        self.pwr_u2.setObjectName("pwr_u2")
        self.gridLayout_2.addWidget(self.pwr_u2, 1, 1, 1, 1)
        self.plotTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dem_q1 = BaseMplCanvas(self.tab_2)
        self.dem_q1.setObjectName("dem_q1")
        self.gridLayout_3.addWidget(self.dem_q1, 0, 0, 1, 1)
        self.dem_q2 = BaseMplCanvas(self.tab_2)
        self.dem_q2.setObjectName("dem_q2")
        self.gridLayout_3.addWidget(self.dem_q2, 0, 1, 1, 1)
        self.dem_u1 = BaseMplCanvas(self.tab_2)
        self.dem_u1.setObjectName("dem_u1")
        self.gridLayout_3.addWidget(self.dem_u1, 1, 0, 1, 1)
        self.dem_u2 = BaseMplCanvas(self.tab_2)
        self.dem_u2.setObjectName("dem_u2")
        self.gridLayout_3.addWidget(self.dem_u2, 1, 1, 1, 1)
        self.plotTabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.plotTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.plotTabWidget.addTab(self.tab_4, "")
        self.verticalLayout_4.addWidget(self.plotTabWidget)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stats_tree = QtWidgets.QTreeWidget(self.groupBox_2)
        self.stats_tree.setColumnCount(2)
        self.stats_tree.setObjectName("stats_tree")
        self.stats_tree.headerItem().setText(0, "Polarimeter")
        self.horizontalLayout_2.addWidget(self.stats_tree)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1551, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.plotTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Polarimeter"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.tab), _translate("MainWindow", "Total power"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.tab_2), _translate("MainWindow", "Demodulated"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.checkBox.setText(_translate("MainWindow", "HA1"))
        self.checkBox_2.setText(_translate("MainWindow", "HA2"))
        self.checkBox_3.setText(_translate("MainWindow", "HA3"))
        self.checkBox_4.setText(_translate("MainWindow", "HB1"))
        self.checkBox_5.setText(_translate("MainWindow", "HB2"))
        self.checkBox_6.setText(_translate("MainWindow", "HB2"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.tab_3), _translate("MainWindow", "LNA biases"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.tab_4), _translate("MainWindow", "Temperatures"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Statistics"))
        self.stats_tree.headerItem().setText(1, _translate("MainWindow", "average"))

from widgets.plot.base import BaseMplCanvas

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

