# -*- encoding: utf-8 -*-

# This file contains the arguments of the pipeline for functional verification of LSPE-STRIP (2023)
# September 29th 2023, Brescia (Italy) - December 5th 2024, Bologna (Italy)

[official_pipeline_args]

########################################################################################################################
# Positional Arguments (mandatory)
########################################################################################################################
subcommand = 'tot'
path_file =  '../data_test/'     # '/mnt/storage/data/HDF5'
start_datetime='2024-02-02 20:00:00'
end_datetime='2024-02-03 00:00:00'
name_pol= "R0 R1" # Set 'all' to parse all 55 polarimeters

########################################################################################################################
# Flags (optional)
########################################################################################################################

# TOML
toml_file_path = "pipeline/config/validation_config/config_tot.toml"

# TS Analysis
thermal_sensors = "false"
ts_sam_exp_med=20.0
ts_sam_tolerance=1.0

# HK Analysis
housekeeping = "false"
# HK properties: V, I, O, M, P
hk_sam_exp_med = "1.4, 1.4, 60.0, 60.0, 60.0"
hk_sam_tolerance = "0.1, 0.1, 0.5, 0.5, 0.5"

# Correlation Analysis
corr_plot= "false"
corr_mat= "false"
cross_corr= "false" # Set "true" for cross correlations
corr_t=0.4

# Scientific Analysis
even_odd_all='A'
scientific="true"
rms="false"
smooth=100
window=10
sam_tolerance=0.005

# Spectral Analysis
fourier="true"
noise_level="true"
# To reach a min freq of ~10^-3 these are the nperseg requested
nperseg=100_000
nperseg_thermal=50

# Spike Analysis
spike_data="false"
spike_fft="false"

# Output dir for plots and reports
output_plot_dir='../RESULTS/PIPELINE'
output_report_dir='../RESULTS/PIPELINE/Reports'
report_to_plot ='../..'
