# -*- encoding: utf-8 -*-

# This file contains the arguments of the pipeline for functional verification of LSPE-STRIP (2023)
# December 29th 2023, Brescia (Italy) - April 15th 2024, Brescia (Italy)

[official_pipeline_args]

########################################################################################################################
# Positional Arguments (mandatory)
########################################################################################################################
subcommand = 'thermal_hk'
path_file =  '../data_test/'     # '/mnt/storage/data/HDF5'
start_datetime='2024-02-02 20:00:00'
end_datetime='2024-02-03 00:00:00'

########################################################################################################################
# Flags (optional)
########################################################################################################################

# TOML
toml_file_path = "pipeline/config/validation_config/config_thermal_hk.toml"

# TS Analysis
ts_sam_exp_med=20.0
ts_sam_tolerance=1.0

# Status
status = 2

# Correlation Analysis
corr_plot= "true"
corr_mat= "true"
corr_t=0.4

# Spectral Analysis
fourier="true"
# To reach a min freq of ~10^-3 this is the nperseg requested
nperseg_thermal=50

# Spike Analysis
spike_data="true"
spike_fft="true"

# Output dir for plots and reports
output_plot_dir='../RESULTS/PIPELINE'
output_report_dir='../RESULTS/PIPELINE/Reports'
report_to_plot ='../..'
