# -*- encoding: utf-8 -*-

# This file contains the arguments of the pipeline for functional verification of LSPE-STRIP (2023)
# December 29th 2023, Brescia (Italy) - April 15th 2024, Brescia (Italy)

[official_pipeline_args]

########################################################################################################################
# Positional Arguments (mandatory)
########################################################################################################################
subcommand = 'pol_hk'
path_file =  '../data_test/'     # '/mnt/storage/data/HDF5'
start_datetime='2024-02-02 20:00:00'
end_datetime='2024-02-03 00:00:00'
name_pol= "B0" # Set 'all' to parse all 55 polarimeters

########################################################################################################################
# Flags (optional)
########################################################################################################################

# TOML
toml_file_path = "pipeline/config/validation_config/config_pol_hk.toml"

# HK Analysis
# HK properties: V, I, O, M, P
hk_sam_exp_med = "1.4, 1.4, 60.0, 60., 60."
hk_sam_tolerance = "0.1, 0.1, 0.5, 0.5, 0.5"

# Correlation Analysis
corr_plot= "true"
corr_mat= "true"
corr_t=0.4

# Output dir for plots and reports
output_plot_dir='../RESULTS/PIPELINE'
output_report_dir='../RESULTS/PIPELINE/Reports'
report_to_plot ='../..'
